import { Contribution } from "./types";

export const placeholderContributions: Contribution[] = [
  {
    id: "1",
    project: "Next.js",
    repo_url: "https://github.com/vercel/next.js",
    description:
      "Fixed a race condition in the App Router's streaming SSR pipeline that caused intermittent hydration mismatches on pages with concurrent data fetches.",
    pr_url: "https://github.com/vercel/next.js/pull/00001",
    status: "merged",
    type: "bug-fix",
    language: "TypeScript",
    stars: 128000,
    merged_at: "2025-11-14",
    created_at: "2025-11-01",
    tags: ["app-router", "streaming", "ssr"],
  },
  {
    id: "2",
    project: "Tailwind CSS",
    repo_url: "https://github.com/tailwindlabs/tailwindcss",
    description:
      "Added support for container query variants using the new `@container` syntax, enabling responsive designs based on parent element size.",
    pr_url: "https://github.com/tailwindlabs/tailwindcss/pull/00002",
    status: "merged",
    type: "feature",
    language: "JavaScript",
    stars: 84000,
    merged_at: "2025-09-20",
    created_at: "2025-09-05",
    tags: ["container-queries", "responsive", "css"],
  },
  {
    id: "3",
    project: "Supabase",
    repo_url: "https://github.com/supabase/supabase",
    description:
      "Improved the realtime subscription API typings to properly infer row types from the schema, reducing boilerplate for typed subscribers.",
    pr_url: "https://github.com/supabase/supabase/pull/00003",
    status: "merged",
    type: "refactor",
    language: "TypeScript",
    stars: 75000,
    merged_at: "2025-08-03",
    created_at: "2025-07-28",
    tags: ["realtime", "typescript", "dx"],
  },
  {
    id: "4",
    project: "React",
    repo_url: "https://github.com/facebook/react",
    description:
      "Updated the `useTransition` documentation with clearer examples showing the difference between urgent and non-urgent state updates.",
    pr_url: "https://github.com/facebook/react/pull/00004",
    status: "merged",
    type: "docs",
    language: "Markdown",
    stars: 230000,
    merged_at: "2025-06-11",
    created_at: "2025-06-08",
    tags: ["docs", "hooks", "concurrent"],
  },
  {
    id: "5",
    project: "Prisma",
    repo_url: "https://github.com/prisma/prisma",
    description:
      "Added `findFirstOrThrow` and `findUniqueOrThrow` helper methods to the Prisma Client to reduce boilerplate null-checks in server code.",
    pr_url: "https://github.com/prisma/prisma/pull/00005",
    status: "open",
    type: "feature",
    language: "TypeScript",
    stars: 40000,
    created_at: "2026-01-15",
    tags: ["client", "dx", "query"],
  },
  {
    id: "6",
    project: "Vite",
    repo_url: "https://github.com/vitejs/vite",
    description:
      "Resolved a memory leak in the HMR module graph that accumulated stale module records after hot-updates in large monorepos.",
    pr_url: "https://github.com/vitejs/vite/pull/00006",
    status: "merged",
    type: "bug-fix",
    language: "TypeScript",
    stars: 68000,
    merged_at: "2025-12-01",
    created_at: "2025-11-22",
    tags: ["hmr", "performance", "memory"],
  },
  {
    id: "7",
    project: "tRPC",
    repo_url: "https://github.com/trpc/trpc",
    description:
      "Wrote end-to-end tests for the `experimental_formData` input transformer to ensure correct behaviour with multipart uploads.",
    pr_url: "https://github.com/trpc/trpc/pull/00007",
    status: "merged",
    type: "test",
    language: "TypeScript",
    stars: 35000,
    merged_at: "2025-10-08",
    created_at: "2025-10-01",
    tags: ["testing", "formdata", "e2e"],
  },
  {
    id: "8",
    project: "shadcn/ui",
    repo_url: "https://github.com/shadcn-ui/ui",
    description:
      "Added an accessible `Combobox` component built on Radix UI primitives with keyboard navigation, search filtering, and multi-select support.",
    pr_url: "https://github.com/shadcn-ui/ui/pull/00008",
    status: "closed",
    type: "feature",
    language: "TypeScript",
    stars: 80000,
    created_at: "2025-07-10",
    tags: ["component", "a11y", "radix"],
  },
];
